# Generated by Django 4.1.13 on 2025-03-15 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_subgoal'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('prayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.prayer')),
                ('sub_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goals.subgoal')),
            ],
        ),
    ]
