export const reciterList = [
  {
    name_ar: "ناصر القطامي",
    name_en: "Nasser Alqatami",
    query: "https://server6.mp3quran.net/qtm",
  },
  {
    name_ar: "ياسر الدوسري",
    name_en: "Yasser Al-Dosari",
    query: "https://server11.mp3quran.net/yasser",
  },
  {
    name_ar: "عبد الرحمن العوسي",
    name_en: "Abdulrahman Aloosi",
    query: "https://server6.mp3quran.net/aloosi",
  },
  {
    name_ar: "مشاري راشد العفاسي",
    name_en: "Mishary Alafasi",
    query: "https://server8.mp3quran.net/afs",
  },
  {
    name_ar: "اسلام صبحي",
    name_en: "Islam Sobhi",
    query: "https://server14.mp3quran.net/islam/Rewayat-Hafs-A-n-Assem",
  },
  {
    name_ar: "فارس عباد",
    name_en: "Fares Abbad",
    query: "https://server8.mp3quran.net/frs_a",
  },
  {
    name_ar: "عبد الباسط عبد الصمد",
    name_en: "Abdulbasit Abdulsamad",
    query: "https://server7.mp3quran.net/basit/Almusshaf-Al-Mojawwad",
  },
  {
    name_ar: "محمد صديق المنشاوي",
    name_en: "Mohammed Siddiq Al-Minshawi",
    query: "https://server10.mp3quran.net/minsh",
  },
  {
    name_ar: "محمد أيوب",
    name_en: "Mohammed Ayyub",
    query: "https://server8.mp3quran.net/ayyub",
  },
  {
    name_ar: "محمد اللحيدان",
    name_en: "Mohammed Al-Lohaidan",
    query: "https://server8.mp3quran.net/lhdan",
  },
  {
    name_ar: "ماهر المعيقلي",
    name_en: "Maher Al Meaqli",
    query: "https://server12.mp3quran.net/maher",
  },
  {
    name_ar: "منصور السالمي",
    name_en: "Mansour Al-Salemi",
    query: "https://server14.mp3quran.net/mansor",
  },
  {
    name_ar: "أحمد النفيس",
    name_en: "Ahmad Al Nufais",
    query: "https://server16.mp3quran.net/nufais/Rewayat-Hafs-A-n-Assem",
  },
];

export const quranList = [
  { name_ar: "سورة الفاتحة", name_en: "Al-Fatiha", query: "001" },
  { name_ar: "سورة البقرة", name_en: "Al-Baqarah", query: "002" },
  { name_ar: "سورة آل عمران", name_en: "Aal-E-Imran", query: "003" },
  { name_ar: "سورة النساء", name_en: "An-Nisa", query: "004" },
  { name_ar: "سورة المائدة", name_en: "Al-Ma'idah", query: "005" },
  { name_ar: "سورة الأنعام", name_en: "Al-An'am", query: "006" },
  { name_ar: "سورة الأعراف", name_en: "Al-A'raf", query: "007" },
  { name_ar: "سورة الأنفال", name_en: "Al-Anfal", query: "008" },
  { name_ar: "سورة التوبة", name_en: "At-Tawbah", query: "009" },
  { name_ar: "سورة يونس", name_en: "Yunus", query: "010" },
  { name_ar: "سورة هود", name_en: "Hud", query: "011" },
  { name_ar: "سورة يوسف", name_en: "Yusuf", query: "012" },
  { name_ar: "سورة الرعد", name_en: "Ar-Ra'd", query: "013" },
  { name_ar: "سورة إبراهيم", name_en: "Ibrahim", query: "014" },
  { name_ar: "سورة الحجر", name_en: "Al-Hijr", query: "015" },
  { name_ar: "سورة النحل", name_en: "An-Nahl", query: "016" },
  { name_ar: "سورة الإسراء", name_en: "Al-Isra", query: "017" },
  { name_ar: "سورة الكهف", name_en: "Al-Kahf", query: "018" },
  { name_ar: "سورة مريم", name_en: "Maryam", query: "019" },
  { name_ar: "سورة طه", name_en: "Taha", query: "020" },
  { name_ar: "سورة الأنبياء", name_en: "Al-Anbiya", query: "021" },
  { name_ar: "سورة الحج", name_en: "Al-Hajj", query: "022" },
  { name_ar: "سورة المؤمنون", name_en: "Al-Mu'minun", query: "023" },
  { name_ar: "سورة النور", name_en: "An-Nur", query: "024" },
  { name_ar: "سورة الفرقان", name_en: "Al-Furqan", query: "025" },
  { name_ar: "سورة الشعراء", name_en: "Ash-Shu'ara", query: "026" },
  { name_ar: "سورة النمل", name_en: "An-Naml", query: "027" },
  { name_ar: "سورة القصص", name_en: "Al-Qasas", query: "028" },
  { name_ar: "سورة العنكبوت", name_en: "Al-Ankabut", query: "029" },
  { name_ar: "سورة الروم", name_en: "Ar-Rum", query: "030" },
  { name_ar: "سورة لقمان", name_en: "Luqman", query: "031" },
  { name_ar: "سورة السجدة", name_en: "As-Sajda", query: "032" },
  { name_ar: "سورة الأحزاب", name_en: "Al-Ahzab", query: "033" },
  { name_ar: "سورة سبأ", name_en: "Saba", query: "034" },
  { name_ar: "سورة فاطر", name_en: "Fatir", query: "035" },
  { name_ar: "سورة يس", name_en: "Ya-Sin", query: "036" },
  { name_ar: "سورة الصافات", name_en: "As-Saffat", query: "037" },
  { name_ar: "سورة ص", name_en: "Sad", query: "038" },
  { name_ar: "سورة الزمر", name_en: "Az-Zumar", query: "039" },
  { name_ar: "سورة غافر", name_en: "Ghafir", query: "040" },
  { name_ar: "سورة فصلت", name_en: "Fussilat", query: "041" },
  { name_ar: "سورة الشورى", name_en: "Ash-Shura", query: "042" },
  { name_ar: "سورة الزخرف", name_en: "Az-Zukhruf", query: "043" },
  { name_ar: "سورة الدخان", name_en: "Ad-Dukhan", query: "044" },
  { name_ar: "سورة الجاثية", name_en: "Al-Jathiya", query: "045" },
  { name_ar: "سورة الأحقاف", name_en: "Al-Ahqaf", query: "046" },
  { name_ar: "سورة محمد", name_en: "Muhammad", query: "047" },
  { name_ar: "سورة الفتح", name_en: "Al-Fath", query: "048" },
  { name_ar: "سورة الحجرات", name_en: "Al-Hujurat", query: "049" },
  { name_ar: "سورة ق", name_en: "Qaf", query: "050" },
  { name_ar: "سورة الذاريات", name_en: "Adh-Dhariyat", query: "051" },
  { name_ar: "سورة الطور", name_en: "At-Tur", query: "052" },
  { name_ar: "سورة النجم", name_en: "An-Najm", query: "053" },
  { name_ar: "سورة القمر", name_en: "Al-Qamar", query: "054" },
  { name_ar: "سورة الرحمن", name_en: "Ar-Rahman", query: "055" },
  { name_ar: "سورة الواقعة", name_en: "Al-Waqi'a", query: "056" },
  { name_ar: "سورة الحديد", name_en: "Al-Hadid", query: "057" },
  { name_ar: "سورة المجادلة", name_en: "Al-Mujadila", query: "058" },
  { name_ar: "سورة الحشر", name_en: "Al-Hashr", query: "059" },
  { name_ar: "سورة الممتحنة", name_en: "Al-Mumtahina", query: "060" },
  { name_ar: "سورة الصف", name_en: "As-Saff", query: "061" },
  { name_ar: "سورة الجمعة", name_en: "Al-Jumu'a", query: "062" },
  { name_ar: "سورة المنافقون", name_en: "Al-Munafiqun", query: "063" },
  { name_ar: "سورة التغابن", name_en: "At-Taghabun", query: "064" },
  { name_ar: "سورة الطلاق", name_en: "At-Talaq", query: "065" },
  { name_ar: "سورة التحريم", name_en: "At-Tahrim", query: "066" },
  { name_ar: "سورة الملك", name_en: "Al-Mulk", query: "067" },
  { name_ar: "سورة القلم", name_en: "Al-Qalam", query: "068" },
  { name_ar: "سورة الحاقة", name_en: "Al-Haqqa", query: "069" },
  { name_ar: "سورة المعارج", name_en: "Al-Ma'arij", query: "070" },
  { name_ar: "سورة نوح", name_en: "Nuh", query: "071" },
  { name_ar: "سورة الجن", name_en: "Al-Jinn", query: "072" },
  { name_ar: "سورة المزمل", name_en: "Al-Muzzammil", query: "073" },
  { name_ar: "سورة المدثر", name_en: "Al-Muddathir", query: "074" },
  { name_ar: "سورة القيامة", name_en: "Al-Qiyama", query: "075" },
  { name_ar: "سورة الإنسان", name_en: "Al-Insan", query: "076" },
  { name_ar: "سورة المرسلات", name_en: "Al-Mursalat", query: "077" },
  { name_ar: "سورة النبأ", name_en: "An-Naba", query: "078" },
  { name_ar: "سورة النازعات", name_en: "An-Nazi'at", query: "079" },
  { name_ar: "سورة عبس", name_en: "Abasa", query: "080" },
  { name_ar: "سورة التكوير", name_en: "At-Takwir", query: "081" },
  { name_ar: "سورة الإنفطار", name_en: "Al-Infitar", query: "082" },
  { name_ar: "سورة المطففين", name_en: "Al-Mutaffifin", query: "083" },
  { name_ar: "سورة الإنشقاق", name_en: "Al-Inshiqaq", query: "084" },
  { name_ar: "سورة البروج", name_en: "Al-Buruj", query: "085" },
  { name_ar: "سورة الطارق", name_en: "At-Tariq", query: "086" },
  { name_ar: "سورة الأعلى", name_en: "Al-A'la", query: "087" },
  { name_ar: "سورة الغاشية", name_en: "Al-Ghashiya", query: "088" },
  { name_ar: "سورة الفجر", name_en: "Al-Fajr", query: "089" },
  { name_ar: "سورة البلد", name_en: "Al-Balad", query: "090" },
  { name_ar: "سورة الشمس", name_en: "Ash-Shams", query: "091" },
  { name_ar: "سورة الليل", name_en: "Al-Lail", query: "092" },
  { name_ar: "سورة الضحى", name_en: "Ad-Duhaa", query: "093" },
  { name_ar: "سورة الشرح", name_en: "Ash-Sharh", query: "094" },
  { name_ar: "سورة التين", name_en: "At-Tin", query: "095" },
  { name_ar: "سورة العلق", name_en: "Al-Alaq", query: "096" },
  { name_ar: "سورة القدر", name_en: "Al-Qadr", query: "097" },
  { name_ar: "سورة البينة", name_en: "Al-Bayyina", query: "098" },
  { name_ar: "سورة الزلزلة", name_en: "Az-Zalzala", query: "099" },
  { name_ar: "سورة العاديات", name_en: "Al-Adiyat", query: "100" },
  { name_ar: "سورة القارعة", name_en: "Al-Qari'a", query: "101" },
  { name_ar: "سورة التكاثر", name_en: "At-Takathur", query: "102" },
  { name_ar: "سورة العصر", name_en: "Al-Asr", query: "103" },
  { name_ar: "سورة الهمزة", name_en: "Al-Humaza", query: "104" },
  { name_ar: "سورة الفيل", name_en: "Al-Fil", query: "105" },
  { name_ar: "سورة قريش", name_en: "Quraysh", query: "106" },
  { name_ar: "سورة الماعون", name_en: "Al-Ma'un", query: "107" },
  { name_ar: "سورة الكوثر", name_en: "Al-Kawthar", query: "108" },
  { name_ar: "سورة الكافرون", name_en: "Al-Kafirun", query: "109" },
  { name_ar: "سورة النصر", name_en: "An-Nasr", query: "110" },
  { name_ar: "سورة المسد", name_en: "Al-Masad", query: "111" },
  { name_ar: "سورة الإخلاص", name_en: "Al-Ikhlas", query: "112" },
  { name_ar: "سورة الفلق", name_en: "Al-Falaq", query: "113" },
  { name_ar: "سورة الناس", name_en: "An-Nas", query: "114" },
];
