# Generated by Django 4.1.13 on 2025-03-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="user_id",
            new_name="user",
        ),
    ]
