# Generated by Django 4.1.13 on 2025-03-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_rename_user_id_goal_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="title",
            new_name="name",
        ),
    ]
