# Generated by Django 4.1.13 on 2025-03-14 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_title_goal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_goals', to='goals.goal')),
            ],
        ),
    ]
