# Generated by Django 4.1.13 on 2025-03-17 12:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_remove_goal_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
