# Generated by Django 4.1.13 on 2025-03-20 15:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0006_alter_goal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
