# Generated by Django 4.1.13 on 2025-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0007_alter_goal_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subgoal",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="goal",
            name="image",
        ),
        migrations.AddField(
            model_name="goal",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="subgoal",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
