# Generated by Django 4.1.13 on 2025-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0008_alter_subgoal_options_remove_goal_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="_progress",
            field=models.IntegerField(db_column="progress", default=0),
        ),
    ]
