# Generated by Django 4.1.13 on 2025-04-13 21:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0009_goal__progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subgoal",
            options={},
        ),
        migrations.RemoveField(
            model_name="goal",
            name="_progress",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="image_url",
        ),
        migrations.AddField(
            model_name="goal",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="subgoal",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
