# Generated by Django 4.1.13 on 2025-04-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0010_alter_subgoal_options_remove_goal__progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="image",
        ),
        migrations.AddField(
            model_name="goal",
            name="image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
