# Generated by Django 4.1.13 on 2025-04-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_clerk_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="clerk_id",
        ),
    ]
