# Generated by Django 4.1.13 on 2025-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_clerk_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clerk_user_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
