# Generated by Django 4.1.13 on 2025-04-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_clerk_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="clerk_user_id",
        ),
    ]
